/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signalprocessing;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.knowm.xchart.QuickChart;
import org.knowm.xchart.XYChart;

/**
 *
 * @author nekrasov
 */
public class Lab02JFrame extends javax.swing.JFrame {

    final int SAW_INDEX = 3;
    
    XYChart signalChart, fftChart;
    final String seriesName = "y(x)";
    
    /**
     * Creates new form Lab02JFrame
     */
    public Lab02JFrame() {
        initComponents();
        
        signalChart = QuickChart.getChart("", "", "", seriesName, new double[1], new double[1]);
        fftChart = QuickChart.getChart("", "", "", seriesName, new double[1], new double[1]);
        
        setSawParamsEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        signalPanel = new javax.swing.JPanel();
        fftPanel = new javax.swing.JPanel();
        fragmentSizeTextField = new javax.swing.JTextField();
        fragmentSizeLabel = new javax.swing.JLabel();
        signalLabel = new javax.swing.JLabel();
        signalComboBox = new javax.swing.JComboBox<>();
        ALabel = new javax.swing.JLabel();
        ATextField = new javax.swing.JTextField();
        TLabel = new javax.swing.JLabel();
        NLabel = new javax.swing.JLabel();
        NTextField = new javax.swing.JTextField();
        TTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signalPanelLayout = new javax.swing.GroupLayout(signalPanel);
        signalPanel.setLayout(signalPanelLayout);
        signalPanelLayout.setHorizontalGroup(
            signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        signalPanelLayout.setVerticalGroup(
            signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fftPanelLayout = new javax.swing.GroupLayout(fftPanel);
        fftPanel.setLayout(fftPanelLayout);
        fftPanelLayout.setHorizontalGroup(
            fftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fftPanelLayout.setVerticalGroup(
            fftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        fragmentSizeTextField.setText("131072");
        fragmentSizeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fragmentSizeTextFieldActionPerformed(evt);
            }
        });

        fragmentSizeLabel.setText("Размер фрагмента:");

        signalLabel.setText("Сигнал:");

        signalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Песня", "Речь", "Музыка", "Пилообразный" }));
        signalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signalComboBoxActionPerformed(evt);
            }
        });

        ALabel.setText("A:");

        ATextField.setText("10");

        TLabel.setText("T:");

        NLabel.setText("N:");

        NTextField.setText("1024");

        TTextField.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(signalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signalComboBox, 0, 125, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fragmentSizeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(NLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(TLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(ALabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fragmentSizeTextField))
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(signalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signalLabel)
                    .addComponent(signalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fragmentSizeLabel)
                    .addComponent(fragmentSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALabel)
                    .addComponent(ATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TLabel)
                    .addComponent(TTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NLabel)
                    .addComponent(NTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(startButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        
        List<Double> signal = null;
        double sampleRate = 1;
        
        if (signalComboBox.getSelectedIndex() == SAW_INDEX) {
            double A = Double.parseDouble(ATextField.getText());
            double T = Double.parseDouble(TTextField.getText());
            int N = Integer.parseInt(NTextField.getText());
            
            StandartSignal sawSignal = new SawSignal(A, T, N);
            signal = sawSignal.getSignal();
            
            sampleRate = N / T;
        } else {
            File soundFile = new File("sounds/the-rolling-stones.wav");
            int fragmentSize = Integer.parseInt(fragmentSizeTextField.getText());
            SoundStream soundStream = new SoundStream();
            
            try {
                signal = soundStream.loadSignal(soundFile, 0, fragmentSize);
                System.out.println("\nРазмер фрагмента: " + signal.size());
            } catch (IOException exc) {
                System.err.println("Не удалось загрузить сигнал");
            }
            
            sampleRate = soundStream.getSampleRate();
        }
        
        updateSignalChart(signal, sampleRate);
        
        FastFourierTransform fastFourierTransform = new FastFourierTransform(signal);
        List<Double> fftModule = fastFourierTransform.getModuleList();
        
        updateFftChart(fftModule);
        
        repaint();
    }//GEN-LAST:event_startButtonActionPerformed

    private void fragmentSizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fragmentSizeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fragmentSizeTextFieldActionPerformed

    private void signalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signalComboBoxActionPerformed
        boolean isSaw = signalComboBox.getSelectedIndex() == SAW_INDEX;
        setSawParamsEnabled(isSaw);
        setSoundParamsEnabled(!isSaw);
    }//GEN-LAST:event_signalComboBoxActionPerformed

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        Graphics2D signalPanelGraphics = (Graphics2D) signalPanel.getGraphics();
        signalChart.paint(signalPanelGraphics, signalPanel.getWidth(), signalPanel.getHeight());
        
        Graphics2D fftPanelGraphics = (Graphics2D) fftPanel.getGraphics();
        fftChart.paint(fftPanelGraphics, fftPanel.getWidth(), fftPanel.getHeight());
    }
    
    void updateSignalChart(List<Double> signal, double sampleRate) {
        int fragmentSize = signal.size();
        double duration = fragmentSize / sampleRate;
        System.out.println("Длительность фрагмента: " + duration + " сек.");
        
        List<Double> x = new ArrayList<>();
        double step = duration / fragmentSize;
        for (int i = 0; i < fragmentSize; i++) {
            x.add(i * step);
        }
        
        updateChart(signalChart, x, signal);
    }
    
    void updateFftChart(List<Double> signal) {
        List<Double> x = new ArrayList<>();
        for (int i = 0, ei = signal.size() / 2; i < ei; i++) {
            x.add((double) i);
        }
        
        updateChart(fftChart, x, signal.subList(0, signal.size() / 2));
    }
    
    void updateChart(XYChart chart, List<Double> x, List<Double> y) {
        chart.updateXYSeries(seriesName, x, y, null);
    }
    
    private void setSoundParamsEnabled(boolean value) {
        fragmentSizeLabel.setEnabled(value);
        fragmentSizeTextField.setEditable(value);
    }
    
    private void setSawParamsEnabled(boolean value) {
        setAEnabled(value);
        setTEnabled(value);
        setNEnabled(value);
    }
    
    void setAEnabled(boolean value) {
        ALabel.setEnabled(value);
        ATextField.setEditable(value);
    }
    
    void setTEnabled(boolean value) {
        TLabel.setEnabled(value);
        TTextField.setEditable(value);
    }
    
    void setNEnabled(boolean value) {
        NLabel.setEnabled(value);
        NTextField.setEditable(value);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALabel;
    private javax.swing.JTextField ATextField;
    private javax.swing.JLabel NLabel;
    private javax.swing.JTextField NTextField;
    private javax.swing.JLabel TLabel;
    private javax.swing.JTextField TTextField;
    private javax.swing.JPanel fftPanel;
    private javax.swing.JLabel fragmentSizeLabel;
    private javax.swing.JTextField fragmentSizeTextField;
    private javax.swing.JComboBox<String> signalComboBox;
    private javax.swing.JLabel signalLabel;
    private javax.swing.JPanel signalPanel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
