/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signalprocessing;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.List;
import org.knowm.xchart.QuickChart;
import org.knowm.xchart.XYChart;

/**
 *
 * @author nekrasov
 */
public class Lab04JFrame extends javax.swing.JFrame {

    final String seriesName = "y(x)";
    
    XYChart signalChart, amplitudeChart, phaseChart, resultChart;
    
    /**
     * Creates new form Lab04JFrame
     */
    public Lab04JFrame() {
        initComponents();
        
        signalChart = QuickChart.getChart("", "", "", seriesName, new double[1], new double[1]);
        amplitudeChart = QuickChart.getChart("", "", "", seriesName, new double[1], new double[1]);
        phaseChart = QuickChart.getChart("", "", "", seriesName, new double[1], new double[1]);
        resultChart = QuickChart.getChart("", "", "", seriesName, new double[1], new double[1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signalPanel = new javax.swing.JPanel();
        signalTypeLabel = new javax.swing.JLabel();
        signalTypeComboBox = new javax.swing.JComboBox<>();
        ALabel = new javax.swing.JLabel();
        ATextField = new javax.swing.JTextField();
        TLabel = new javax.swing.JLabel();
        TTextField = new javax.swing.JTextField();
        tauLabel = new javax.swing.JLabel();
        tauTextField = new javax.swing.JTextField();
        NLabel = new javax.swing.JLabel();
        NTextField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        amplitudePanel = new javax.swing.JPanel();
        resultPanel = new javax.swing.JPanel();
        phasePanel = new javax.swing.JPanel();
        transformLabel = new javax.swing.JLabel();
        transformComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout signalPanelLayout = new javax.swing.GroupLayout(signalPanel);
        signalPanel.setLayout(signalPanelLayout);
        signalPanelLayout.setHorizontalGroup(
            signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        signalPanelLayout.setVerticalGroup(
            signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        signalTypeLabel.setText("Тип сигнала:");

        signalTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Прямоугольный", "Пилообразный", "Треугольный" }));
        signalTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signalTypeComboBoxActionPerformed(evt);
            }
        });

        ALabel.setText("A:");

        ATextField.setText("10");

        TLabel.setText("T:");

        TTextField.setText("5");

        tauLabel.setText("tau:");

        tauTextField.setText("3");

        NLabel.setText("N:");

        NTextField.setText("512");

        startButton.setText("Старт");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout amplitudePanelLayout = new javax.swing.GroupLayout(amplitudePanel);
        amplitudePanel.setLayout(amplitudePanelLayout);
        amplitudePanelLayout.setHorizontalGroup(
            amplitudePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        amplitudePanelLayout.setVerticalGroup(
            amplitudePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout phasePanelLayout = new javax.swing.GroupLayout(phasePanel);
        phasePanel.setLayout(phasePanelLayout);
        phasePanelLayout.setHorizontalGroup(
            phasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        phasePanelLayout.setVerticalGroup(
            phasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        transformLabel.setText("Преобразование:");

        transformComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Уолша", "Адамара" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TLabel)
                            .addComponent(ALabel)
                            .addComponent(signalTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(signalTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(transformLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(transformComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ATextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NLabel)
                                    .addComponent(tauLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(NTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(tauTextField, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addComponent(startButton))
                .addContainerGap(635, Short.MAX_VALUE))
            .addComponent(amplitudePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(phasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(signalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amplitudePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signalTypeLabel)
                    .addComponent(signalTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transformLabel)
                    .addComponent(transformComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ALabel)
                            .addComponent(ATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TLabel)
                            .addComponent(TTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tauLabel)
                            .addComponent(tauTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NLabel)
                            .addComponent(NTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signalTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signalTypeComboBoxActionPerformed
        setTauEnabled(signalTypeComboBox.getSelectedIndex() == 0);
    }//GEN-LAST:event_signalTypeComboBoxActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        double A = Double.parseDouble(ATextField.getText());
        double T = Double.parseDouble(TTextField.getText());
        int N = Integer.parseInt(NTextField.getText());
        
        StandartSignal standartSignal;
        
        switch (signalTypeComboBox.getSelectedIndex()) {
            case 0: {
                double tau = Double.parseDouble(tauTextField.getText());
                standartSignal = new RectSignal(A, T, N, tau);
                break;
            }
                
            case 1:
                standartSignal = new SawSignal(A, T, N);
                break;
                
            default:
                standartSignal = new TriangleSignal(A, T, N);
                break;
        }
        
        List<Double> signal = standartSignal.getSignal();
        Common.updateSignalChart(signalChart, signal, N / T, seriesName);
        
        boolean isWalsh = transformComboBox.getSelectedIndex() == 0;
        Adamar adamar = new Adamar(signal.size(), isWalsh);
        
        RectTransform transform = new RectTransform(signal, adamar, false);
        List<Double> amplitude = transform.getAmplitude();
        Common.updateSignalChart(amplitudeChart, amplitude, 1, seriesName);
        
        List<Double> phase = transform.getPhase();
        Common.updateSignalChart(phaseChart , phase, 1, seriesName);
        
        RectTransform inverseTransform = new RectTransform(transform.getTransformation(), adamar, true);
        List<Double> result = inverseTransform.getTransformation();
        Common.updateSignalChart(resultChart, result, N / T, seriesName);
        
        repaint();
    }//GEN-LAST:event_startButtonActionPerformed

    private void setTauEnabled(boolean value) {
        tauLabel.setEnabled(value);
        tauTextField.setEditable(value);
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        Graphics2D signalPanelGraphics = (Graphics2D) signalPanel.getGraphics();
        signalChart.paint(signalPanelGraphics, signalPanel.getWidth(), signalPanel.getHeight());
        
        Graphics2D amplitudePanelGraphics = (Graphics2D) amplitudePanel.getGraphics();
        amplitudeChart.paint(amplitudePanelGraphics, amplitudePanel.getWidth(), amplitudePanel.getHeight());
        
        Graphics2D phasePanelGraphics = (Graphics2D) phasePanel.getGraphics();
        phaseChart.paint(phasePanelGraphics, phasePanel.getWidth(), phasePanel.getHeight());
        
        Graphics2D resultPanelGraphics = (Graphics2D) resultPanel.getGraphics();
        resultChart.paint(resultPanelGraphics, resultPanel.getWidth(), resultPanel.getHeight());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALabel;
    private javax.swing.JTextField ATextField;
    private javax.swing.JLabel NLabel;
    private javax.swing.JTextField NTextField;
    private javax.swing.JLabel TLabel;
    private javax.swing.JTextField TTextField;
    private javax.swing.JPanel amplitudePanel;
    private javax.swing.JPanel phasePanel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JPanel signalPanel;
    private javax.swing.JComboBox<String> signalTypeComboBox;
    private javax.swing.JLabel signalTypeLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel tauLabel;
    private javax.swing.JTextField tauTextField;
    private javax.swing.JComboBox<String> transformComboBox;
    private javax.swing.JLabel transformLabel;
    // End of variables declaration//GEN-END:variables
}
